name: Docker-CI/CD

on:
  push:
    branches:
      - main
      - soc
  pull_request:
    branches:
      - main
      - soc
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Compose
        run: |
          cp .env.example .env
          docker-compose -f docker-compose.yml up -d

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: SSH into the VM 
        run:
          gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME}} --zone=${{ secrets.GCP_ZONE }} --command "git clone ${{secret.REPO_URL}}"
